version: '3.9'

services:
  app:
    build: .
    container_name: habit-app
    ports:
      - "5050:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/habit_db
      - FLASK_ENV=development
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: habit-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: habit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
