apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: habit-tracker
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - port: 5000       # the port the Flask app is listening on
      targetPort: 5000 # inside the container
      nodePort: 30500  # exposed on your local machine (via minikube)
